/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Monorepo API
 * Template API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary Health check
 */
export const getHealthResponse = zod.object({
  "status": zod.enum(['ok']),
  "ts": zod.string().datetime({}),
  "db": zod.enum(['ok', 'error'])
})


/**
 * @summary List example records
 */
export const listExamplesQueryParams = zod.object({
  "orgId": zod.string().optional()
})

export const listExamplesResponseItem = zod.object({
  "id": zod.string().uuid(),
  "orgId": zod.string(),
  "name": zod.string(),
  "createdAt": zod.string().datetime({}),
  "updatedAt": zod.string().datetime({})
})
export const listExamplesResponse = zod.array(listExamplesResponseItem)


/**
 * @summary Create an example record
 */




export const createExampleBody = zod.object({
  "orgId": zod.string().min(1),
  "name": zod.string().min(1)
})
