/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Monorepo API
 * Template API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { apiFetch } from './client';
export type HealthResponseStatus = typeof HealthResponseStatus[keyof typeof HealthResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthResponseStatus = {
  ok: 'ok',
} as const;

export type HealthResponseDb = typeof HealthResponseDb[keyof typeof HealthResponseDb];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthResponseDb = {
  ok: 'ok',
  error: 'error',
} as const;

export interface HealthResponse {
  status: HealthResponseStatus;
  ts: string;
  db: HealthResponseDb;
}

export interface Example {
  id: string;
  orgId: string;
  name: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateExampleInput {
  /** @minLength 1 */
  orgId: string;
  /** @minLength 1 */
  name: string;
}

export type ListExamplesParams = {
/**
 * @minLength 1
 */
orgId: string;
};

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Health check
 */
export const getHealth = (
    
 options?: SecondParameter<typeof apiFetch>,signal?: AbortSignal
) => {
      
      
      return apiFetch<HealthResponse>(
      {url: `/health`, method: 'GET', signal
    },
      options);
    }
  



export const getGetHealthQueryKey = () => {
    return [
    `/health`
    ] as const;
    }

    
export const getGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHealthQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealth>>> = ({ signal }) => getHealth(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData> & { queryKey: QueryKey }
}

export type GetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getHealth>>>
export type GetHealthQueryError = unknown


/**
 * @summary Health check
 */

export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>, request?: SecondParameter<typeof apiFetch>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetHealthQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary List example records
 */
export const listExamples = (
    params: ListExamplesParams,
 options?: SecondParameter<typeof apiFetch>,signal?: AbortSignal
) => {
      
      
      return apiFetch<Example[]>(
      {url: `/api/example`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListExamplesQueryKey = (params?: ListExamplesParams,) => {
    return [
    `/api/example`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListExamplesQueryOptions = <TData = Awaited<ReturnType<typeof listExamples>>, TError = unknown>(params: ListExamplesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listExamples>>, TError, TData>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListExamplesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listExamples>>> = ({ signal }) => listExamples(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listExamples>>, TError, TData> & { queryKey: QueryKey }
}

export type ListExamplesQueryResult = NonNullable<Awaited<ReturnType<typeof listExamples>>>
export type ListExamplesQueryError = unknown


/**
 * @summary List example records
 */

export function useListExamples<TData = Awaited<ReturnType<typeof listExamples>>, TError = unknown>(
 params: ListExamplesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listExamples>>, TError, TData>, request?: SecondParameter<typeof apiFetch>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListExamplesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Create an example record
 */
export const createExample = (
    createExampleInput: CreateExampleInput,
 options?: SecondParameter<typeof apiFetch>,signal?: AbortSignal
) => {
      
      
      return apiFetch<Example>(
      {url: `/api/example`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createExampleInput, signal
    },
      options);
    }
  


export const getCreateExampleMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createExample>>, TError,{data: CreateExampleInput}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createExample>>, TError,{data: CreateExampleInput}, TContext> => {

const mutationKey = ['createExample'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createExample>>, {data: CreateExampleInput}> = (props) => {
          const {data} = props ?? {};

          return  createExample(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateExampleMutationResult = NonNullable<Awaited<ReturnType<typeof createExample>>>
    export type CreateExampleMutationBody = CreateExampleInput
    export type CreateExampleMutationError = unknown

    /**
 * @summary Create an example record
 */
export const useCreateExample = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createExample>>, TError,{data: CreateExampleInput}, TContext>, request?: SecondParameter<typeof apiFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createExample>>,
        TError,
        {data: CreateExampleInput},
        TContext
      > => {

      const mutationOptions = getCreateExampleMutationOptions(options);

      return useMutation(mutationOptions);
    }
